# Generated by Django 4.0 on 2022-01-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticateUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentaccount',
            name='publishable_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentaccount',
            name='secret_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
