# Generated by Django 4.0 on 2021-12-25 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticateUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.FileField(blank=True, null=True, upload_to=file_management.models.get_upload_path)),
                ('other_link', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('is_public', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('expire_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticateUser.user')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='permitted_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_file', through='file_management.UserFilePermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticateUser.user'),
        ),
    ]
