# Generated by Django 4.0 on 2022-01-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_userfilepermission_file_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilepermission',
            name='file_password',
        ),
        migrations.AddField(
            model_name='file',
            name='file_password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
