# Generated by Django 4.0 on 2022-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_remove_userfilepermission_file_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
